package rds

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// QueryShareDBInstancesService invokes the rds.QueryShareDBInstancesService API synchronously
func (client *Client) QueryShareDBInstancesService(request *QueryShareDBInstancesServiceRequest) (response *QueryShareDBInstancesServiceResponse, err error) {
	response = CreateQueryShareDBInstancesServiceResponse()
	err = client.DoAction(request, response)
	return
}

// QueryShareDBInstancesServiceWithChan invokes the rds.QueryShareDBInstancesService API asynchronously
func (client *Client) QueryShareDBInstancesServiceWithChan(request *QueryShareDBInstancesServiceRequest) (<-chan *QueryShareDBInstancesServiceResponse, <-chan error) {
	responseChan := make(chan *QueryShareDBInstancesServiceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.QueryShareDBInstancesService(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// QueryShareDBInstancesServiceWithCallback invokes the rds.QueryShareDBInstancesService API asynchronously
func (client *Client) QueryShareDBInstancesServiceWithCallback(request *QueryShareDBInstancesServiceRequest, callback func(response *QueryShareDBInstancesServiceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *QueryShareDBInstancesServiceResponse
		var err error
		defer close(result)
		response, err = client.QueryShareDBInstancesService(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// QueryShareDBInstancesServiceRequest is the request struct for api QueryShareDBInstancesService
type QueryShareDBInstancesServiceRequest struct {
	*requests.RpcRequest
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
}

// QueryShareDBInstancesServiceResponse is the response struct for api QueryShareDBInstancesService
type QueryShareDBInstancesServiceResponse struct {
	*responses.BaseResponse
	RequestId        string           `json:"RequestId" xml:"RequestId"`
	Code             string           `json:"Code" xml:"Code"`
	Message          string           `json:"Message" xml:"Message"`
	Success          bool             `json:"Success" xml:"Success"`
	ShareDBInstances ShareDBInstances `json:"ShareDBInstances" xml:"ShareDBInstances"`
}

// CreateQueryShareDBInstancesServiceRequest creates a request to invoke QueryShareDBInstancesService API
func CreateQueryShareDBInstancesServiceRequest() (request *QueryShareDBInstancesServiceRequest) {
	request = &QueryShareDBInstancesServiceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Rds", "2013-05-28", "QueryShareDBInstancesService", "rds", "openAPI")
	request.Method = requests.POST
	return
}

// CreateQueryShareDBInstancesServiceResponse creates a response to parse from QueryShareDBInstancesService response
func CreateQueryShareDBInstancesServiceResponse() (response *QueryShareDBInstancesServiceResponse) {
	response = &QueryShareDBInstancesServiceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
