package scdn

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// ISPProportionData is a nested struct in scdn response
type ISPProportionData struct {
	AvgObjectSize   string `json:"AvgObjectSize" xml:"AvgObjectSize"`
	AvgResponseRate string `json:"AvgResponseRate" xml:"AvgResponseRate"`
	Bps             string `json:"Bps" xml:"Bps"`
	IspEname        string `json:"IspEname" xml:"IspEname"`
	AvgResponseTime string `json:"AvgResponseTime" xml:"AvgResponseTime"`
	Qps             string `json:"Qps" xml:"Qps"`
	Proportion      string `json:"Proportion" xml:"Proportion"`
	TotalQuery      string `json:"TotalQuery" xml:"TotalQuery"`
	ISP             string `json:"ISP" xml:"ISP"`
	BytesProportion string `json:"BytesProportion" xml:"BytesProportion"`
	TotalBytes      string `json:"TotalBytes" xml:"TotalBytes"`
	ReqErrRate      string `json:"ReqErrRate" xml:"ReqErrRate"`
}
