package cloudcallcenter

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// CallCenterInstance is a nested struct in cloudcallcenter response
type CallCenterInstance struct {
	DirectoryId         string                      `json:"DirectoryId" xml:"DirectoryId"`
	StorageBucket       string                      `json:"StorageBucket" xml:"StorageBucket"`
	DomainName          string                      `json:"DomainName" xml:"DomainName"`
	InstanceName        string                      `json:"InstanceName" xml:"InstanceName"`
	Owner               string                      `json:"Owner" xml:"Owner"`
	InstanceDescription string                      `json:"InstanceDescription" xml:"InstanceDescription"`
	StorageMaxSize      int                         `json:"StorageMaxSize" xml:"StorageMaxSize"`
	StorageMaxDays      int                         `json:"StorageMaxDays" xml:"StorageMaxDays"`
	CreatedTime         int64                       `json:"CreatedTime" xml:"CreatedTime"`
	InstanceId          string                      `json:"InstanceId" xml:"InstanceId"`
	ConsoleUrl          string                      `json:"ConsoleUrl" xml:"ConsoleUrl"`
	MaxOnlineAgents     int                         `json:"MaxOnlineAgents" xml:"MaxOnlineAgents"`
	Status              string                      `json:"Status" xml:"Status"`
	TenantId            string                      `json:"TenantId" xml:"TenantId"`
	Admin               AdminInListInstances        `json:"Admin" xml:"Admin"`
	PhoneNumbers        PhoneNumbersInListInstances `json:"PhoneNumbers" xml:"PhoneNumbers"`
}
