package dbfs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// SnapshotsItem is a nested struct in dbfs response
type SnapshotsItem struct {
	Status              string `json:"Status" xml:"Status"`
	CreationTime        string `json:"CreationTime" xml:"CreationTime"`
	Progress            string `json:"Progress" xml:"Progress"`
	SourceFsSize        int    `json:"SourceFsSize" xml:"SourceFsSize"`
	RetentionDays       int    `json:"RetentionDays" xml:"RetentionDays"`
	RemainTime          int    `json:"RemainTime" xml:"RemainTime"`
	LastModifiedTime    string `json:"LastModifiedTime" xml:"LastModifiedTime"`
	SnapshotType        string `json:"SnapshotType" xml:"SnapshotType"`
	SnapshotName        string `json:"SnapshotName" xml:"SnapshotName"`
	Description         string `json:"Description" xml:"Description"`
	SourceFsId          string `json:"SourceFsId" xml:"SourceFsId"`
	SnapshotId          string `json:"SnapshotId" xml:"SnapshotId"`
	Category            string `json:"Category" xml:"Category"`
	SourceFsStripeWidth int    `json:"SourceFsStripeWidth" xml:"SourceFsStripeWidth"`
}
