package ehpc

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// ClusterInfoSimple is a nested struct in ehpc response
type ClusterInfoSimple struct {
	Status          string         `json:"Status" xml:"Status"`
	SchedulerType   string         `json:"SchedulerType" xml:"SchedulerType"`
	CreateTime      string         `json:"CreateTime" xml:"CreateTime"`
	ImageOwnerAlias string         `json:"ImageOwnerAlias" xml:"ImageOwnerAlias"`
	OsTag           string         `json:"OsTag" xml:"OsTag"`
	InstanceType    string         `json:"InstanceType" xml:"InstanceType"`
	AccountType     string         `json:"AccountType" xml:"AccountType"`
	Count           int            `json:"Count" xml:"Count"`
	RegionId        string         `json:"RegionId" xml:"RegionId"`
	Description     string         `json:"Description" xml:"Description"`
	ZoneId          string         `json:"ZoneId" xml:"ZoneId"`
	LoginNodes      string         `json:"LoginNodes" xml:"LoginNodes"`
	Name            string         `json:"Name" xml:"Name"`
	ImageId         string         `json:"ImageId" xml:"ImageId"`
	Id              string         `json:"Id" xml:"Id"`
	Managers        Managers       `json:"Managers" xml:"Managers"`
	Computes        Computes       `json:"Computes" xml:"Computes"`
	TotalResources  TotalResources `json:"TotalResources" xml:"TotalResources"`
	UsedResources   UsedResources  `json:"UsedResources" xml:"UsedResources"`
}
