package kms

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeKmsService invokes the kms.DescribeKmsService API synchronously
func (client *Client) DescribeKmsService(request *DescribeKmsServiceRequest) (response *DescribeKmsServiceResponse, err error) {
	response = CreateDescribeKmsServiceResponse()
	err = client.DoAction(request, response)
	return
}

// DescribeKmsServiceWithChan invokes the kms.DescribeKmsService API asynchronously
func (client *Client) DescribeKmsServiceWithChan(request *DescribeKmsServiceRequest) (<-chan *DescribeKmsServiceResponse, <-chan error) {
	responseChan := make(chan *DescribeKmsServiceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DescribeKmsService(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DescribeKmsServiceWithCallback invokes the kms.DescribeKmsService API asynchronously
func (client *Client) DescribeKmsServiceWithCallback(request *DescribeKmsServiceRequest, callback func(response *DescribeKmsServiceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DescribeKmsServiceResponse
		var err error
		defer close(result)
		response, err = client.DescribeKmsService(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DescribeKmsServiceRequest is the request struct for api DescribeKmsService
type DescribeKmsServiceRequest struct {
	*requests.RpcRequest
}

// DescribeKmsServiceResponse is the response struct for api DescribeKmsService
type DescribeKmsServiceResponse struct {
	*responses.BaseResponse
	ServiceState string `json:"ServiceState" xml:"ServiceState"`
	RequestId    string `json:"RequestId" xml:"RequestId"`
}

// CreateDescribeKmsServiceRequest creates a request to invoke DescribeKmsService API
func CreateDescribeKmsServiceRequest() (request *DescribeKmsServiceRequest) {
	request = &DescribeKmsServiceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Kms", "2016-01-20", "DescribeKmsService", "kms", "openAPI")
	request.Method = requests.POST
	return
}

// CreateDescribeKmsServiceResponse creates a response to parse from DescribeKmsService response
func CreateDescribeKmsServiceResponse() (response *DescribeKmsServiceResponse) {
	response = &DescribeKmsServiceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
