package cloudfw

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// DataItemInDescribeNatFirewallControlPolicy is a nested struct in cloudfw response
type DataItemInDescribeNatFirewallControlPolicy struct {
	Destination           string   `json:"Destination" xml:"Destination"`
	Order                 int      `json:"Order" xml:"Order"`
	DestPortGroup         string   `json:"DestPortGroup" xml:"DestPortGroup"`
	SourceType            string   `json:"SourceType" xml:"SourceType"`
	DnsResultTime         int64    `json:"DnsResultTime" xml:"DnsResultTime"`
	DnsResult             string   `json:"DnsResult" xml:"DnsResult"`
	AclUuid               string   `json:"AclUuid" xml:"AclUuid"`
	DestPortType          string   `json:"DestPortType" xml:"DestPortType"`
	Source                string   `json:"Source" xml:"Source"`
	DestinationType       string   `json:"DestinationType" xml:"DestinationType"`
	HitTimes              int      `json:"HitTimes" xml:"HitTimes"`
	HitLastTime           int64    `json:"HitLastTime" xml:"HitLastTime"`
	DestPort              string   `json:"DestPort" xml:"DestPort"`
	Description           string   `json:"Description" xml:"Description"`
	AclAction             string   `json:"AclAction" xml:"AclAction"`
	Proto                 string   `json:"Proto" xml:"Proto"`
	Release               string   `json:"Release" xml:"Release"`
	SourceGroupType       string   `json:"SourceGroupType" xml:"SourceGroupType"`
	DestinationGroupType  string   `json:"DestinationGroupType" xml:"DestinationGroupType"`
	NatGatewayId          string   `json:"NatGatewayId" xml:"NatGatewayId"`
	DomainResolveType     int      `json:"DomainResolveType" xml:"DomainResolveType"`
	SpreadCnt             string   `json:"SpreadCnt" xml:"SpreadCnt"`
	CreateTime            int64    `json:"CreateTime" xml:"CreateTime"`
	ModifyTime            int64    `json:"ModifyTime" xml:"ModifyTime"`
	ApplicationNameList   []string `json:"ApplicationNameList" xml:"ApplicationNameList"`
	DestinationGroupCidrs []string `json:"DestinationGroupCidrs" xml:"DestinationGroupCidrs"`
	DestPortGroupPorts    []string `json:"DestPortGroupPorts" xml:"DestPortGroupPorts"`
	SourceGroupCidrs      []string `json:"SourceGroupCidrs" xml:"SourceGroupCidrs"`
}
