package schedulerx3

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// Record is a nested struct in schedulerx3 response
type Record struct {
	Event          string          `json:"Event" xml:"Event"`
	Leader         string          `json:"Leader" xml:"Leader"`
	IntranetDomain string          `json:"IntranetDomain" xml:"IntranetDomain"`
	AlarmType      string          `json:"AlarmType" xml:"AlarmType"`
	AlarmStatus    string          `json:"AlarmStatus" xml:"AlarmStatus"`
	Content        string          `json:"Content" xml:"Content"`
	Creator        string          `json:"Creator" xml:"Creator"`
	AccessToken    string          `json:"AccessToken" xml:"AccessToken"`
	NoticeContacts string          `json:"NoticeContacts" xml:"NoticeContacts"`
	VpcId          string          `json:"VpcId" xml:"VpcId"`
	EngineType     string          `json:"EngineType" xml:"EngineType"`
	JobType        string          `json:"JobType" xml:"JobType"`
	Duration       int64           `json:"Duration" xml:"Duration"`
	RouteStrategy  int             `json:"RouteStrategy" xml:"RouteStrategy"`
	JobId          int64           `json:"JobId" xml:"JobId"`
	Time           string          `json:"Time" xml:"Time"`
	ClusterId      string          `json:"ClusterId" xml:"ClusterId"`
	SpInstanceId   string          `json:"SpInstanceId" xml:"SpInstanceId"`
	EngineVersion  string          `json:"EngineVersion" xml:"EngineVersion"`
	ClusterSpec    string          `json:"ClusterSpec" xml:"ClusterSpec"`
	MaxConcurrency int             `json:"MaxConcurrency" xml:"MaxConcurrency"`
	JobNum         int             `json:"JobNum" xml:"JobNum"`
	Id             int64           `json:"Id" xml:"Id"`
	WorkerAddr     string          `json:"WorkerAddr" xml:"WorkerAddr"`
	Parameters     string          `json:"Parameters" xml:"Parameters"`
	StartTime      string          `json:"StartTime" xml:"StartTime"`
	EndTime        string          `json:"EndTime" xml:"EndTime"`
	Calendar       string          `json:"Calendar" xml:"Calendar"`
	EnableLog      bool            `json:"EnableLog" xml:"EnableLog"`
	JobExecutionId string          `json:"JobExecutionId" xml:"JobExecutionId"`
	ExecutorNum    int64           `json:"ExecutorNum" xml:"ExecutorNum"`
	Title          string          `json:"Title" xml:"Title"`
	ChargeType     string          `json:"ChargeType" xml:"ChargeType"`
	CreateTime     string          `json:"CreateTime" xml:"CreateTime"`
	ScheduleTime   string          `json:"ScheduleTime" xml:"ScheduleTime"`
	Executor       string          `json:"Executor" xml:"Executor"`
	NoticeConfig   string          `json:"NoticeConfig" xml:"NoticeConfig"`
	ProductType    int             `json:"ProductType" xml:"ProductType"`
	ServerIp       string          `json:"ServerIp" xml:"ServerIp"`
	ClusterName    string          `json:"ClusterName" xml:"ClusterName"`
	JobName        string          `json:"JobName" xml:"JobName"`
	InternetDomain string          `json:"InternetDomain" xml:"InternetDomain"`
	DataTime       string          `json:"DataTime" xml:"DataTime"`
	Updater        string          `json:"Updater" xml:"Updater"`
	TimeType       int             `json:"TimeType" xml:"TimeType"`
	MaxJobs        int             `json:"MaxJobs" xml:"MaxJobs"`
	Status         int             `json:"Status" xml:"Status"`
	AlarmMessage   string          `json:"AlarmMessage" xml:"AlarmMessage"`
	Result         string          `json:"Result" xml:"Result"`
	AlarmChannel   string          `json:"AlarmChannel" xml:"AlarmChannel"`
	AlarmContacts  string          `json:"AlarmContacts" xml:"AlarmContacts"`
	Attempt        int             `json:"Attempt" xml:"Attempt"`
	WorkAddr       string          `json:"WorkAddr" xml:"WorkAddr"`
	AppName        string          `json:"AppName" xml:"AppName"`
	TriggerType    int             `json:"TriggerType" xml:"TriggerType"`
	VSwitches      []VswitchesItem `json:"VSwitches" xml:"VSwitches"`
}
