package r_kvstore

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// InstancesItem is a nested struct in r_kvstore response
type InstancesItem struct {
	VpcId             string          `json:"VpcId" xml:"VpcId"`
	CharacterType     string          `json:"CharacterType" xml:"CharacterType"`
	VswitchId         string          `json:"VswitchId" xml:"VswitchId"`
	InstanceClass     string          `json:"InstanceClass" xml:"InstanceClass"`
	MaintainStartTime string          `json:"MaintainStartTime" xml:"MaintainStartTime"`
	CreateTime        string          `json:"CreateTime" xml:"CreateTime"`
	ConnectionDomain  string          `json:"ConnectionDomain" xml:"ConnectionDomain"`
	MaintainEndTime   string          `json:"MaintainEndTime" xml:"MaintainEndTime"`
	StorageType       string          `json:"StorageType" xml:"StorageType"`
	InstanceId        string          `json:"InstanceId" xml:"InstanceId"`
	BandWidth         int64           `json:"BandWidth" xml:"BandWidth"`
	CurrentBandWidth  int64           `json:"CurrentBandWidth" xml:"CurrentBandWidth"`
	EngineVersion     string          `json:"EngineVersion" xml:"EngineVersion"`
	RegionId          string          `json:"RegionId" xml:"RegionId"`
	InstanceName      string          `json:"InstanceName" xml:"InstanceName"`
	ZoneId            string          `json:"ZoneId" xml:"ZoneId"`
	ClusterName       string          `json:"ClusterName" xml:"ClusterName"`
	InstanceStatus    string          `json:"InstanceStatus" xml:"InstanceStatus"`
	Engine            string          `json:"Engine" xml:"Engine"`
	ShardCount        int             `json:"ShardCount" xml:"ShardCount"`
	CustomId          string          `json:"CustomId" xml:"CustomId"`
	ProxyCount        int             `json:"ProxyCount" xml:"ProxyCount"`
	ClusterId         string          `json:"ClusterId" xml:"ClusterId"`
	InstanceNodeList  []InstanceNodes `json:"InstanceNodeList" xml:"InstanceNodeList"`
}
