package vs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// Template is a nested struct in vs response
type Template struct {
	Id            string        `json:"Id" xml:"Id"`
	Name          string        `json:"Name" xml:"Name"`
	Description   string        `json:"Description" xml:"Description"`
	Type          string        `json:"Type" xml:"Type"`
	Region        string        `json:"Region" xml:"Region"`
	OssBucket     string        `json:"OssBucket" xml:"OssBucket"`
	OssEndpoint   string        `json:"OssEndpoint" xml:"OssEndpoint"`
	OssFilePrefix string        `json:"OssFilePrefix" xml:"OssFilePrefix"`
	Trigger       string        `json:"Trigger" xml:"Trigger"`
	StartTime     string        `json:"StartTime" xml:"StartTime"`
	EndTime       string        `json:"EndTime" xml:"EndTime"`
	Interval      int64         `json:"Interval" xml:"Interval"`
	Retention     int64         `json:"Retention" xml:"Retention"`
	FileFormat    string        `json:"FileFormat" xml:"FileFormat"`
	JpgOverwrite  string        `json:"JpgOverwrite" xml:"JpgOverwrite"`
	JpgSequence   string        `json:"JpgSequence" xml:"JpgSequence"`
	JpgOnDemand   string        `json:"JpgOnDemand" xml:"JpgOnDemand"`
	Mp4           string        `json:"Mp4" xml:"Mp4"`
	Flv           string        `json:"Flv" xml:"Flv"`
	HlsM3u8       string        `json:"HlsM3u8" xml:"HlsM3u8"`
	HlsTs         string        `json:"HlsTs" xml:"HlsTs"`
	Callback      string        `json:"Callback" xml:"Callback"`
	CreatedTime   string        `json:"CreatedTime" xml:"CreatedTime"`
	TransConfigs  []TransConfig `json:"TransConfigs" xml:"TransConfigs"`
}
